#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: license-check

# Run this workflow every time a new commit push to the repository
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
env:
    DASH_TOOL_VERSION: 1.1.0

jobs:
    third-party-license-check:
        runs-on: ubuntu-latest
        steps:
            - name: Set Up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'temurin'
            - name: Checkout
              uses: actions/checkout@v5
            - name: Install all required NPM packages
              working-directory: ./
              run: npm install
            - name: Download Eclipse Dash Tool Jar
              run: wget https://repo.eclipse.org/service/local/repositories/dash-licenses-releases/content/org/eclipse/dash/org.eclipse.dash.licenses/${{ env.DASH_TOOL_VERSION }}/org.eclipse.dash.licenses-${{ env.DASH_TOOL_VERSION }}.jar
            - name: Run License Validation
              run: java -jar org.eclipse.dash.licenses-${{ env.DASH_TOOL_VERSION }}.jar package-lock.json
              # To be enabled once the initial IP check is completed by EF team.
              continue-on-error: true
