#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: ui-docker-image

on:
    workflow_dispatch:
        inputs:
            ReleaseVersion:
                type: string
                description: Enter the version of the Docker image
                required: true

env:
    BOT_USER_NAME: eclipse-xpanse-bot
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run install dependencies
              run: npm install

            - name: Build Application
              run: npm run build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Packages
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ env.BOT_USER_NAME }}
                  password: ${{ secrets.BOT_GITHUB_DOCKER_TOKEN }}

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5.6.1
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build Docker Image and Push
              uses: docker/build-push-action@v6.11.0
              with:
                  context: .
                  file: docker/Dockerfile
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.ReleaseVersion }}
                  labels: ${{ steps.meta.outputs.labels }}
                  provenance: false
